name: Deploy react app
on: 
  push:
    branches: 
      - main
jobs:
  deploy: 
    name: deploy app
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: ["12.x"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install packages
        run: npm install
      - name: registry github user
        run: /
          git config --global user.email <antonio.mardones98@hotmail.com>
          git condig --global user.name <antoniomardoness98>
      - name: deploy the app
        run: npm run deploy
        env:
          GH_TOKEN: ${{secrets.5e8a1c426d3d09765a5d1bcd2d700912e9f7192a}}